[package]
name = "floor-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
ctrlc = "3.2.3"
regex = "1.6.0"
tungstenite = "0.17.3"
url = "2.3.1"
